[colors]

[colors]
background=282828ff
text=fbf1c7ff
prompt=fabd2fff
placeholder=83a598ff
input=b8bb26ff
match=83a598ff
selection=b8bb2680
selection-text=fbf1c7ff
selection-match=282828ff
counter=fabd2fff
border=b8bb26ff


; background=#1f1f1fff
; text=#c6d0f5ff
; prompt=#b5bfe2ff
; placeholder=#838ba7ff
; input=#c6d0f5ff
; match=#8caaeeff
; selection=#626880ff
; selection-text=#c6d0f5ff
; selection-match=#8caaeeff
; counter=#838ba7ff
; border=#8caaeeff

[border]
width=2
radius=7
include=/home/red-vortex/.config/fuzzel/themes/noctalia
