# custom default shell
set-option -g default-shell /usr/bin/fish
set-option -g default-command /usr/bin/fish
# tmux reload shortcut
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Init TPM (custom path)
run '~/.config/tmux/plugins/tpm/tpm'

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -ga terminal-features ",*:RGB"
set -g mode-keys vi

# prefix key change (C-b to C-a)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# base index of tmux session
set-option -g base-index 1
set-option -g pane-base-index 1

# restore window number
bind _ move-window -r
set-option -g renumber-windows on

# mouse on
set-option -g mouse on

# terminal output history line
set-option -g history-limit 100000

# tmux title/path
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}" # split horizontally -
bind '%' split-window -h -c "#{pane_current_path}" # split vertically |

# others options
# of this features if they are causing problems
set-option -s focus-events on
set-option -s extended-keys on
set-option -s escape-time 0

######
# styling

# color variables
FG=#c3ccf1
BLUE=#8caaee
DARK_GREY=#626880
TEXT_COLOR=#2f2836

# powerline character unicode variables
HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"
TRIANGLE_OPEN="#(printf '\uE0B2')"
TRIANGLE_CLOSE="#(printf '\uE0B0')"


# tmux status bar 
set-option -g message-style bg=${DARK_GREY},fg=${FG}
set-option -g message-command-style bg=${DARK_GREY},fg=${FG}
set-option -g mode-style bg=${DARK_GREY},fg=${FG}
set-option -g popup-style "bg=#1f1f1f"
set-option -g popup-border-lines rounded
set-option -g status-position top
set-option -g status-style bg=${DARK_GREY},fg=${FG}
set-option -g status-justify centre
set-option -g status-left "\
#[bg=${BLUE},fg=${TEXT_COLOR}] #S \
#[fg=${BLUE},bg=default]${TRIANGLE_CLOSE} \
#[fg=${BLUE},bg=default]${HALF_ROUND_OPEN}\
#[bg=${BLUE},fg=${TEXT_COLOR}]  #(basename #{pane_current_path})\
#[fg=${BLUE},bg=default]${HALF_ROUND_CLOSE}\
"

set-option -g status-right "\
#[fg=${BLUE},bg=default]${TRIANGLE_OPEN}\
#[bg=${BLUE},fg=${TEXT_COLOR}]  #{user}@#H\
#[bg=${BLUE},fg=${TEXT_COLOR}]  #(cat /sys/class/power_supply/BAT0/capacity)%\
"

set-option -g status-left-length 100
set-option -g status-right-length 100

set-option -g window-status-format " #I:#W "
set-option -g window-status-current-format "\
#[fg=${BLUE},bg=default]${HALF_ROUND_OPEN}\
#[bg=${BLUE},fg=${TEXT_COLOR}]#I:\
#[bg=${BLUE},fg=${TEXT_COLOR}]#W\
#[fg=${BLUE},bg=default]${HALF_ROUND_CLOSE}\
"
# keybindings for tmux
# split pane focus keybind
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# alt+num switch window
bind -n M-1 select-window -t :=1
bind -n M-2 select-window -t :=2
bind -n M-3 select-window -t :=3
bind -n M-4 select-window -t :=4
bind -n M-5 select-window -t :=5
bind -n M-6 select-window -t :=6
bind -n M-7 select-window -t :=7
bind -n M-8 select-window -t :=8
bind -n M-9 select-window -t :=9

# full screen (resize split pane)
unbind m
bind m resize-pane -Z


# ##### Display Popups ##### 
bind C-p display-popup \
  -d "#{pane_current_path}" \
  -w 90% \
  -h 85% \
  -E "tmux new-session -d -s popup 2>/dev/null; tmux set-option -t popup status off; tmux attach -t popup"

# yazi file manger setting for image preview in yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# new-session create automatic 
bind-key N run-shell "~/.local/bin/tmux-workspace"
# close current active session
unbind q
bind-key q run-shell "~/.local/bin/tmux-workspace-kill"
